name = "autocaption-pro"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[[env.production.kv_namespaces]]
binding = "KV_STORE"
id = "your-kv-namespace-id"

[env.production.vars]
STRIPE_PUBLISHABLE_KEY = "pk_test_51S41DLK0wxQPIemdaalU9BVg1jjgj9CVioVGDpo76bO9jbAUr8bqACD4j6QA63hJcZX1VlSORYAvGNgtR313hXuX000dSfBOcj"