name: Claude Health Agent

on:
  # still allow manual runs
  workflow_dispatch: {}
  # run periodically to keep things healthy
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  # allow other workflows to call this one
  workflow_call:
    inputs:
      site_url:
        description: "Production site URL"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          GH_REPO:  ${{ secrets.GH_REPO }}
          # prefer input, else repo variable, else default
          SITE_URL: ${{ inputs.site_url || vars.SITE_URL || 'https://autocaption-pro.pages.dev' }}
        run: python agent.py
