name: Export Transactions
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Fetch transactions
        run: curl -s https://autocaption-pro.pages.dev/transactions > transactions.json
      - name: Convert JSON to CSV
        run: jq -r '.transactions | (first | keys_unsorted) as $keys | $keys, map([.[ $keys[] ]])[] | @csv' transactions.json > transactions.csv
      - name: Commit CSV
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add transactions.csv
          git commit -m "Daily export of transactions"
          git push
